version: '3'  # version of compose format 

services:
  laptop-service:
    build: ./laptop  
    volumes:
      - ./laptop:/usr/src/app 
    ports:
      - 5001:80  # host:container
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    depends_on:
      - db

  website:
    image: php:apache  
    volumes:
      - ./website:/var/www/html 
    ports:
      - 5000:80  # host:container
    depends_on:
      - laptop-service  # website is not going to work unless laptop-service is running

  web:
    build: ./DockerMongo
    command: python -u app.py
    ports:
      - "5010:5000"
    volumes:
      - ./DockerMongo:/todo
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo:3.0.2





